# Generated by Django 3.2.13 on 2023-09-11 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0002_story_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='status',
            field=models.CharField(default='pending', max_length=50),
            preserve_default=False,
        ),
    ]
