# Generated by Django 3.2.13 on 2023-09-11 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0003_chapter_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='content',
            field=models.TextField(default='hopefully this works'),
            preserve_default=False,
        ),
    ]
