# Generated by Django 3.2.13 on 2023-09-11 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0004_chapter_content'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='rating',
        ),
        migrations.RemoveField(
            model_name='story',
            name='reviews',
        ),
        migrations.RemoveField(
            model_name='story',
            name='setting',
        ),
        migrations.RemoveField(
            model_name='story',
            name='status',
        ),
    ]
