# Generated by Django 3.2.13 on 2023-09-12 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0005_auto_20230911_1705'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=3),
        ),
        migrations.AddField(
            model_name='story',
            name='reviews',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_story.review'),
        ),
        migrations.AddField(
            model_name='story',
            name='status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
