# Generated by Django 3.2.13 on 2023-09-12 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0007_alter_story_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='order',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
