# Generated by Django 3.2.13 on 2023-09-12 13:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0008_alter_chapter_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chapterId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_story.chapter'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='storyId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api_story.story'),
        ),
    ]
