# Generated by Django 3.2.13 on 2023-09-13 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0010_remove_reply_reviewid'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='epilogue',
            field=models.TextField(default='This is an epilogue'),
            preserve_default=False,
        ),
    ]
