# Generated by Django 3.2.13 on 2023-09-13 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_story', '0011_story_epilogue'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='title',
            field=models.CharField(default='New title', max_length=50),
            preserve_default=False,
        ),
    ]
