# Generated by Django 3.2.13 on 2023-09-10 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0003_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='level',
            field=models.CharField(default='Student of Space', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='userType',
            field=models.CharField(default='Reader', max_length=50),
        ),
    ]
