# Generated by Django 3.2.13 on 2023-09-10 08:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0004_auto_20230910_1116'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('chapterId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=100)),
                ('setting', models.CharField(max_length=100)),
                ('age_group', models.CharField(max_length=50)),
                ('prologue', models.TextField()),
                ('status', models.CharField(max_length=50)),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('authorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('reviews', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api_user.review')),
            ],
        ),
        migrations.AddField(
            model_name='review',
            name='storyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.story'),
        ),
        migrations.AddField(
            model_name='review',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('commentId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.comment')),
                ('reviewId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.review')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='comment',
            name='storyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.story'),
        ),
        migrations.AddField(
            model_name='comment',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='chapter',
            name='storyId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_user.story'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='userId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
