# Generated by Django 3.2.13 on 2023-09-13 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_user', '0006_auto_20230910_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about',
            field=models.TextField(null=True),
        ),
    ]
